### ISSUE TITLE
First example: 'utils' not found

### ISSUE THREAD

**Issue by Thomas-M-H-Hope** [alan-turing-institute/skpro#1]
The first example in your documentation (DensityBaseline) does not run right on my machine: it throws a 'module not found' exception at the call to 'utils'.

This might be a python version problem (I am using 3.6), so perhaps it's not an error in the normal sense - though I don't see any specification that the package required a particular python version. Apologies if I missed it: in any case, I fixed it by importing matplotlib instead: i.e. 

import matplotlib.pyplot as plt
plt.scatter(y_test, y_pred)

instead of:

import utils
utils.plot_performance(y_test, y_pred)

**Comment by Thomas-M-H-Hope** [comment]
Ah - it seems this does run fine when using the 'bleeding edge' implementation. Just didn't have the relevant 'utils.py' in the stable release.

**Comment by frthjf** [comment]
Hi, thanks for raising this. The utils module is not part of the actual skpro package but just a python module in the examples folder [here](https://github.com/alan-turing-institute/skpro/tree/master/examples). To make the import work you have to make sure that the ``utils.py`` file is present at the same directory of your python script. Alternatively, you can copy the plot_performance function directly from the [utils.py](https://github.com/alan-turing-institute/skpro/blob/master/examples/utils.py).
Hope that helps.
